# ФАЙЛ: prometheus.yml
# НАЗНАЧЕНИЕ: Конфигурация Prometheus

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'go-app'
    static_configs:
      - targets: ['host.docker.internal:8080']  # ← Этот адрес работает только если сервер запущен на хосте